import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const brandId = searchParams.get('brandId')

    if (!brandId) {
      return NextResponse.json({ error: 'Brand ID required' }, { status: 400 })
    }

    // In production, fetch brand data from database
    const brandData = {
      brandName: 'TechFlow Solutions',
      tagline: 'Streamlining Tomorrow\'s Technology',
      colorPalette: [
        { name: 'Primary Blue', hex: '#2563EB' },
        { name: 'Secondary Teal', hex: '#0D9488' },
        { name: 'Accent Orange', hex: '#EA580C' },
        { name: 'Neutral Gray', hex: '#6B7280' },
        { name: 'Light Background', hex: '#F8FAFC' }
      ],
      typography: {
        primary: 'Inter',
        secondary: 'Roboto',
        headings: 'Poppins'
      },
      brandVoice: 'Professional, innovative, trustworthy, approachable',
      logoUrls: [
        'https://example.com/logo-primary.png',
        'https://example.com/logo-white.png',
        'https://example.com/logo-black.png'
      ]
    }

    // Create ZIP file
    const zip = new JSZip()

    // Add brand guidelines PDF (mock content)
    const brandGuidelinesPDF = `
# ${brandData.brandName} Brand Guidelines

## Brand Identity
**Tagline:** ${brandData.tagline}

## Color Palette
${brandData.colorPalette.map(color => `- ${color.name}: ${color.hex}`).join('\n')}

## Typography
- Primary: ${brandData.typography.primary}
- Secondary: ${brandData.typography.secondary}
- Headings: ${brandData.typography.headings}

## Brand Voice
${brandData.brandVoice}

## Logo Usage
- Use primary logo on light backgrounds
- Use white logo on dark backgrounds
- Maintain minimum clear space of 2x logo height
- Never stretch or distort the logo
    `

    zip.file('Brand_Guidelines.md', brandGuidelinesPDF)

    // Add color palette file
    const colorPaletteCSS = `
/* ${brandData.brandName} Color Palette */
:root {
${brandData.colorPalette.map((color, i) => `  --color-${color.name.toLowerCase().replace(' ', '-')}: ${color.hex};`).join('\n')}
}

/* Utility Classes */
${brandData.colorPalette.map(color => `
.bg-${color.name.toLowerCase().replace(' ', '-')} { background-color: ${color.hex}; }
.text-${color.name.toLowerCase().replace(' ', '-')} { color: ${color.hex}; }
.border-${color.name.toLowerCase().replace(' ', '-')} { border-color: ${color.hex}; }
`).join('')}
    `

    zip.file('colors.css', colorPaletteCSS)

    // Add README
    const readme = `
# ${brandData.brandName} Brand Package

This package contains all the assets and guidelines for your brand identity.

## Contents:
- Brand_Guidelines.md - Complete brand guidelines
- colors.css - CSS color variables and utility classes
- logos/ - Logo files in various formats

## Usage:
1. Review the brand guidelines document
2. Use the provided color palette consistently
3. Follow typography recommendations
4. Maintain logo usage standards

Generated by BrandGenie AI
    `

    zip.file('README.md', readme)

    // Generate ZIP
    const zipData = await zip.generateAsync({ type: 'uint8array' })
    const zipBuffer = Buffer.from(zipData)

    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${brandData.brandName.replace(/\s+/g, '_')}_Brand_Package.zip"`
      }
    })

  } catch (error) {
    console.error('Download error:', error)
    return NextResponse.json({ error: 'Download failed' }, { status: 500 })
  }
}