import { chromium } from 'playwright';
import fs from 'fs';
const base=process.env.SMOKE_BASE_URL;
const pageData={};
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext();
const page=await ctx.newPage();
await page.goto(`${base}/launch`,{waitUntil:'domcontentloaded',timeout:120000});
await page.waitForTimeout(2000);
await page.locator('textarea').first().fill('Unauth debug idea long enough to submit and trigger verification modal with secure link flow.');
await page.locator('input[type="email"]').first().fill('morganclint76@gmail.com');
await page.getByRole('button',{name:/Build My 90-Day Launch Plan/i}).click();
await page.waitForTimeout(15000);
pageData.url = page.url();
pageData.body = (await page.locator('body').innerText()).slice(0,15000);
fs.mkdirSync('.tmp/smoke-prod-browser',{recursive:true});
await page.screenshot({path:'.tmp/smoke-prod-browser/unauth-post-submit.png',fullPage:true});
fs.writeFileSync('.tmp/smoke-prod-browser/unauth-post-submit.txt', pageData.body);
console.log(pageData.body);
await browser.close();
